name: project ci

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: project build

    runs-on: ubuntu-latest
    steps:
      - name: step1 - checkout source code
        uses: actions/checkout@v3

      - name: step2 - setup node
        uses: actions/setup-node@v3
        with:
            node-version: [ 16.x ]

      - name: step3 - install & compile package
        run:
          yarn add yarn run lint tsc

